sudo: required
services:
  - docker

before_install:
  - docker build -t luisalen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true luisalen/react-test npm test

after_success:
  - docker build -t luisalen/multi-client ./client
  - docker build -t luisalen/multi-nginx ./nginx
  - docker build -t luisalen/multi-server ./server
  - docker build -t luisalen/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the images to do cker hub
  - docker push luisalen/multi-client
  - docker push luisalen/multi-nginx
  - docker push luisalen/multi-server
  - docker push luisalen/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: "elasticbeanstalk-us-east-1-657338965286"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
